"""Initial migration

Revision ID: c561a2d0efb0
Revises: 
Create Date: 2024-07-11 09:01:41.286166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c561a2d0efb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hutang3',
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('barang', sa.String(length=100), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('kode')
    )
    op.drop_table('hutang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hutang',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), nullable=False),
    sa.Column('harga', sa.FLOAT(), nullable=False),
    sa.Column('barang', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hutang3')
    # ### end Alembic commands ###
